# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."litellm_db" = {
    image = "postgres:16";
    environment = {
      "POSTGRES_DB" = "litellm";
      "POSTGRES_PASSWORD" = "dbpassword9090";
      "POSTGRES_USER" = "llmproxy";
    };
    volumes = [
      "litellm_postgres_data:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -d litellm -U llmproxy"
      "--health-interval=1s"
      "--health-retries=10"
      "--health-timeout=5s"
      "--network-alias=db"
      "--network=unifiedllm_default"
    ];
  };
  systemd.services."docker-litellm_db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-unifiedllm_default.service"
      "docker-volume-litellm_postgres_data.service"
    ];
    requires = [
      "docker-network-unifiedllm_default.service"
      "docker-volume-litellm_postgres_data.service"
    ];
    partOf = [
      "docker-compose-unifiedllm-root.target"
    ];
    wantedBy = [
      "docker-compose-unifiedllm-root.target"
    ];
  };
  virtualisation.oci-containers.containers."unifiedllm-litellm" = {
    image = "docker.litellm.ai/berriai/litellm:main-stable";
    environment = {
      "DATABASE_URL" = "postgresql://llmproxy:dbpassword9090@db:5432/litellm";
      "LITELLM_MASTER_KEY" = "sk-1234";
      "STORE_MODEL_IN_DB" = "True";
      "STORE_PROMPT_IN_SPEND_LOGS" = "True";
    };
    # volumes = [
    #   "/etc/nixos/hosts/desktop/litellm-config.yaml:/app/config.yaml:rw"
    # ];
    ports = [
      "192.168.100.10:4000:4000/tcp"
    ];
    # cmd = [ "--config" "/app/config.yaml" ];
    dependsOn = [
      "litellm_db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=python3 -c \"import urllib.request; urllib.request.urlopen('http://localhost:4000/health/liveliness')\""
      "--health-interval=30s"
      "--health-retries=3"
      "--health-start-period=40s"
      "--health-timeout=10s"
      "--network-alias=litellm"
      "--network=unifiedllm_default"
    ];
  };
  systemd.services."docker-unifiedllm-litellm" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-unifiedllm_default.service"
    ];
    requires = [
      "docker-network-unifiedllm_default.service"
    ];
    partOf = [
      "docker-compose-unifiedllm-root.target"
    ];
    wantedBy = [
      "docker-compose-unifiedllm-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-unifiedllm_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f unifiedllm_default";
    };
    script = ''
      docker network inspect unifiedllm_default || docker network create unifiedllm_default
    '';
    partOf = [ "docker-compose-unifiedllm-root.target" ];
    wantedBy = [ "docker-compose-unifiedllm-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-litellm_postgres_data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect litellm_postgres_data || docker volume create litellm_postgres_data
    '';
    partOf = [ "docker-compose-unifiedllm-root.target" ];
    wantedBy = [ "docker-compose-unifiedllm-root.target" ];
  };

  # Builds
  systemd.services."docker-build-unifiedllm-litellm" = {
    path = [ pkgs.docker pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/ontu/programming/litellm
      docker build -t docker.litellm.ai/berriai/litellm:main-stable --build-arg target=runtime .
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-unifiedllm-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
